[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables needed for production
# Set these in Netlify dashboard:
# GOOGLE_GEMINI_API_KEY = your_api_key_here 